name: e2e & API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Selenium and Axios Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Chrome for Selenium tests
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Setup Firefox for Selenium tests
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest
        
    - name: Setup Microsoft Edge for Selenium tests
      uses: browser-actions/setup-edge@v1
      with:
        edge-version: stable
    
    - name: Install and start WebDrivers
      run: |
        # Chrome setup
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
        echo "Chrome version: $CHROME_VERSION"
        npm install -g chromedriver@$CHROME_VERSION
        chromedriver --version
        nohup chromedriver --port=4444 --whitelisted-ips="" &
        echo "ChromeDriver started"
        
        # Firefox setup
        npm install -g geckodriver
        geckodriver --version
        nohup geckodriver &
        echo "GeckoDriver started"
        
        # Edge setup
        EDGE_VERSION=$(microsoft-edge --version | cut -d " " -f3 | cut -d "." -f1)
        echo "Edge version: $EDGE_VERSION" 
        npm install -g edgedriver
        nohup msedgedriver &
        echo "EdgeDriver started"
        
        # Wait for drivers to start
        sleep 5
      
    - name: Run all tests
      run: npm run test:e2e:all
      env:
        CI: true
      
    - name: Generate coverage report
      run: npm run coverage
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/
        if-no-files-found: ignore
        
    - name: Upload coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage/
        if-no-files-found: ignore