name: e2e & API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Chrome for Selenium tests
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Start Chrome Driver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
        echo "Chrome version: $CHROME_VERSION"
        npm install -g chromedriver@$CHROME_VERSION
        chromedriver --version
        nohup chromedriver --port=4444 &
        
    - name: Run tests
      run: npm run test:run
      
    - name: Generate coverage report
      run: npm run coverage
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/
        
    - name: Upload coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage/