name: Daily Smoke Tests

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run smoke tests
      run: npm run test:smoke
